name: Deploy React App
on: push
jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test App
        run: npm run test
      - name: Lint App
        run: npm run lint
      - name: Build App
        run: npm run build
      - name: Deploy
        run: echo Deploying...